### ISSUE TITLE
can't test 

### ISSUE THREAD

**Issue by dingning94** [sergiomsilva/alpr-unconstrained#8]
$ bash run.sh samples/ /tmp/output /tmp/output/results.csv
Press any key to continue...
--2018-09-19 23:11:51--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/lp-detector/wpod-net.h5
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/lp-detector/wpod-net.h5’ not modified on server. Omitting download.

--2018-09-19 23:11:53--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/lp-detector/wpod-net.json
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/lp-detector/wpod-net.json’ not modified on server. Omitting download.

--2018-09-19 23:11:54--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/ocr/ocr-net.cfg
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/ocr/ocr-net.cfg’ not modified on server. Omitting download.

--2018-09-19 23:11:55--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/ocr/ocr-net.names
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/ocr/ocr-net.names’ not modified on server. Omitting download.

--2018-09-19 23:11:56--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/ocr/ocr-net.weights
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/ocr/ocr-net.weights’ not modified on server. Omitting download.

--2018-09-19 23:11:58--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/ocr/ocr-net.data
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/ocr/ocr-net.data’ not modified on server. Omitting download.

--2018-09-19 23:11:59--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/vehicle-detector/yolo-voc.cfg
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/vehicle-detector/yolo-voc.cfg’ not modified on server. Omitting download.

--2018-09-19 23:12:03--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/vehicle-detector/voc.data
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/vehicle-detector/voc.data’ not modified on server. Omitting download.

--2018-09-19 23:12:05--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/vehicle-detector/yolo-voc.weights
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/vehicle-detector/yolo-voc.weights’ not modified on server. Omitting download.

--2018-09-19 23:12:08--  http://www.inf.ufrgs.br/~smsilva/alpr-unconstrained/data/vehicle-detector/voc.names
Resolving www.inf.ufrgs.br (www.inf.ufrgs.br)... 143.54.11.16
Connecting to www.inf.ufrgs.br (www.inf.ufrgs.br)|143.54.11.16|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘data/vehicle-detector/voc.names’ not modified on server. Omitting download.

  File "vehicle-detection.py", line 34
    print 'Searching for vehicles using YOLO...'
                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Searching for vehicles using YOLO...')?
  File "license-plate-detection.py", line 29
    print 'Searching for license plates using WPOD-NET'
                                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Searching for license plates using WPOD-NET')?
  File "license-plate-ocr.py", line 28
    print 'Performing OCR...'
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Performing OCR...')?
Traceback (most recent call last):
  File "gen-outputs.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
rm: cannot remove '/tmp/output/*_lp.png': No such file or directory
rm: cannot remove '/tmp/output/*car.png': No such file or directory
rm: cannot remove '/tmp/output/*_cars.txt': No such file or directory
rm: cannot remove '/tmp/output/*_lp.txt': No such file or directory
rm: cannot remove '/tmp/output/*_str.txt': No such file or directory

How to solve this problem? thank you

**Comment by zoidburg** [comment]
maybe you are using python3, the print is stated as a function so try to add parenthesis in the print lines;
and looks like cv2 module is missing, so check it and try to install opencv-python

**Comment by dingning94** [comment]
thanks for your suggestion,the previous question has been solved,but i have encountered some other problems,as shown below.

layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   240 x  80 x   3   ->   240 x  80 x  32  0.033 BFLOPs
    1 max          2 x 2 / 2   240 x  80 x  32   ->   120 x  40 x  32
    2 conv     64  3 x 3 / 1   120 x  40 x  32   ->   120 x  40 x  64  0.177 BFLOPs
    3 max          2 x 2 / 2   120 x  40 x  64   ->    60 x  20 x  64
    4 conv    128  3 x 3 / 1    60 x  20 x  64   ->    60 x  20 x 128  0.177 BFLOPs
    5 conv     64  1 x 1 / 1    60 x  20 x 128   ->    60 x  20 x  64  0.020 BFLOPs
    6 conv    128  3 x 3 / 1    60 x  20 x  64   ->    60 x  20 x 128  0.177 BFLOPs
    7 max          2 x 2 / 2    60 x  20 x 128   ->    30 x  10 x 128
    8 conv    256  3 x 3 / 1    30 x  10 x 128   ->    30 x  10 x 256  0.177 BFLOPs
    9 conv    128  1 x 1 / 1    30 x  10 x 256   ->    30 x  10 x 128  0.020 BFLOPs
   10 conv    256  3 x 3 / 1    30 x  10 x 128   ->    30 x  10 x 256  0.177 BFLOPs
   11 conv    512  3 x 3 / 1    30 x  10 x 256   ->    30 x  10 x 512  0.708 BFLOPs
   12 conv    256  3 x 3 / 1    30 x  10 x 512   ->    30 x  10 x 256  0.708 BFLOPs
   13 conv    512  3 x 3 / 1    30 x  10 x 256   ->    30 x  10 x 512  0.708 BFLOPs
   14 conv     80  1 x 1 / 1    30 x  10 x 512   ->    30 x  10 x  80  0.025 BFLOPs
   15 detection
mask_scale: Using default '1.000000'
Loading weights from data/ocr/ocr-net.weights...Done!
Performing OCR...
rm: cannot remove '/tmp/output/*_lp.png': No such file or directory
rm: cannot remove '/tmp/output/*_lp.txt': No such file or directory
rm: cannot remove '/tmp/output/*_str.txt': No such file or directory


Execution to the ocr part reported that the file is missing,is it because the downloaded file is partially missing?
if you see the time to answer, please thank you for you for your help

**Comment by zoidburg** [comment]
#9 
#4 
please check these issues and try to modify the cfg file, it worked for me

**Comment by sergiomsilva** [comment]
@dingning94 still having problems? Sorry for the delay, I was out of office.

**Comment by dingning94** [comment]
i have found this question and deal with it, Does the model have a demo that can directly detect video?

**Comment by sergiomsilva** [comment]
@dingning94 unfortunately no, but I think it is easy to test using some tool like ffmpeg to convert the video into a sequence of images.
